server:  
    port: 8083
    #address: localhost
    context-path: /
spring:
    freemarker:
        allow-request-override: false
        cache: true
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        suffix: .html
        template-loader-path: classpath:/templates/ftl
        request-context-attribute: request
    datasource:
        name: caoyong
        url: jdbc:mysql://localhost:3306/caoyong?characterEncoding=UTF-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    dubbo:
        application:
            name: service-cms
        registry:
            address: zookeeper://192.168.128.128:2181
        protocol:
            name: dubbo
            port: 20882
        scan: com.caoyong
    activemq:
        broker-url: tcp://192.168.128.128:61616
        user: admin
        password: admin
        pool:
            enabled: false
            max-connections: 5
    data:
        solr:
            host: http://192.168.128.128:8080/solr/collection1
mybatis:
    typeAliasesPackage: com.caoyong.core.bean
    mapperLocations: classpath*:dao/**/*.xml
jedis:
  pool:
    host: 192.168.128.128
    port: 6379
    timeout: 20000
    config:
        maxIdle: 50
        maxTotal: 200
        maxWaitMillis: 10000
        minIdle: 8
        timeBetweenEvictionRunsMillis: 30000
        numTestsPerEvictionRun: 10
        minEvictableIdleTimeMillis: 60000