server:  
    port: 8086
    #address: localhost
    context-path: /
spring:
    datasource:
        name: caoyong
        url: jdbc:mysql://localhost:3306/caoyong?characterEncoding=UTF-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    dubbo:
        application:
            name: service-product
        registry:
            address: zookeeper://192.168.128.128:2181
        protocol:
            name: dubbo
            port: 20881
        scan: com.caoyong
    activemq:
        broker-url: tcp://192.168.128.128:61616
        user: admin
        password: admin
        pool:
            enabled: false
            max-connections: 5
    jms:
        template:
            default-destination: productId
        pub-sub-domain: true
    data:
        solr:
            host: http://192.168.128.128:8080/solr/collection1
mybatis:
    typeAliasesPackage: com.caoyong.core.bean
    mapperLocations: classpath*:dao/**/*.xml